layout_spectrum: 0.7180451
typography_spectrum: 0.7577873
color:
  saturation: 1
  lightness: 0.9103115
  brandStrength: 1
  brandColors:
    - '#6D665C'
    - '#BEB490'
    - '#312F27'
    - '#FCF1BE'
    - '#FB7F43'
  rhythmicContrast: 0.7126746
name: MONTCO GYMNASTICS
